spring:
  # jpa
  datasource:
    url: jdbc:mysql://localhost:3306/wbl?useUnicode=true&serverTimezone=UTC
    username: wbldev
    password: wisebackdev12
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect